### ISSUE TITLE
Erreur d'execution de la commande nsecure auto express

### ISSUE THREAD

**Issue by fouzo09** [NodeSecure/cli#121]
Je viens d'installer nodesecure/cli mais je rencontre une erreur lors de la commande nsecure auto express
`node:internal/modules/cjs/loader:956
  const err = new Error(message);
              ^

Error: Cannot find module 'tslib'
Require stack:
- /usr/lib/node_modules/@nodesecure/cli/node_modules/ts-results/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /usr/lib/node_modules/@nodesecure/cli/node_modules/ts-results/index.js:12:19
    at /usr/lib/node_modules/@nodesecure/cli/node_modules/ts-results/index.js:3:17
    at Object.<anonymous> (/usr/lib/node_modules/@nodesecure/cli/node_modules/ts-results/index.js:9:3)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/node_modules/@nodesecure/cli/node_modules/ts-results/index.js'
  ]
}
`

**Comment by fraxken** [comment]
Hello @fouzo09. Nous avons une piste, je regarde pour corriger cela dans le week-end. Merci d'avoir ouvert une issue.

**Comment by fraxken** [comment]
Le problème est corrigé sur la dernière version patch `2.1.1`. Nous n'avons pas l'erreur chez nous néanmoins, je te laisse revenir vers nous si tu reproduit encore l'erreur.
