### ISSUE TITLE
Cannot read properties of undefined :/

### ISSUE THREAD

**Issue by blephy** [NodeSecure/cli#123]
Hello,

node : 18.11.0
nsecure: 2.1.1

After a run with `nsecure cwd`, i'm getting this error : 

```shell
file:///Users/***/.nvm/versions/node/v18.11.0/lib/node_modules/@nodesecure/cli/src/commands/scanner.js:47
  const { depth: maxDepth = 4, output, nolock, full, vulnerabilityStrategy } = opts;
                 ^

TypeError: Cannot read properties of undefined (reading 'depth')
    at Module.cwd (file:///Users/***/.nvm/versions/node/v18.11.0/lib/node_modules/@nodesecure/cli/src/commands/scanner.js:47:18)
    at file:///Users/***/.nvm/versions/node/v18.11.0/lib/node_modules/@nodesecure/cli/bin/index.js:46:28
    at o.parse (/Users/***/.nvm/versions/node/v18.11.0/lib/node_modules/@nodesecure/cli/node_modules/sade/lib/index.js:1:3402)
    at file:///Users/***/.nvm/versions/node/v18.11.0/lib/node_modules/@nodesecure/cli/bin/index.js:97:6
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Same issue with some arguments `nsecure cwd -d 10`

**Comment by blephy** [comment]
@fraxken 👌
